/*
-- Query: SELECT * FROM `hunspell-ms`.wordlists
-- Date: 2019-11-22 10:52
*/
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (1,'a',NULL,0,'اه','Huruf pertama abjad Rumi.',NULL,'Kamus Dewan Edisi Keempat','sr Utk melahirkan kegirangan atau menyatakan persetujuan.','Itu dia, ~, macam itulah caranya!','Kamus Dewan Edisi Keempat','sr Utk menunjukkan terlupa akan sesuatu.','Nama bukunya ... ~, nanti saya cuba ingatkan!','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,'ꦄ','ꨀ','ꥆ','ᨀ');
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (2,'AA',NULL,0,NULL,'kep Asia-Afrika.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (3,'AB',NULL,0,NULL,'kep Anggaran belanja.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (4,'aba',NULL,0,'اب','~-daba hama, kuman.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦲꦧ',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (5,'aba-aba',NULL,0,'اب۲','Id Kata(-kata) perintah dlm latihan tentera (senaman) dll.','“Satu ...,” ~ Wit dr kerusinya.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦲꦧ​꧇꧒',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (6,'abad',NULL,0,'ابد','Jangka masa seratus tahun (atau satu drpd jangka masa seratus tahun yg berurutan yg dimulai dgn kejadian yg terpenting, iaitu Hijrah Nabi Muhammad SAW bagi Tahun Hijrah atau kelahiran Nabi Isa bagi Tahun Masihi), kurun.','Dlm ~ ke-15 tarikh Masihi (~ ke-9 tarikh Hijrah) Melaka berkuasa di Asia Tenggara. ~ emas zaman sesuatu bangsa atau negara mencapai puncak kejayaan, zaman kegemilangan (gemilang).','Kamus Dewan Edisi Keempat','Beberapa ~ yg lampau beberapa ratus tahun yg lalu.','~ kedua puluh jangka masa dr tahun 1901 hingga ke tahun 2000.','Kamus Dewan Edisi Keempat','~ pertengahan','~ tengah zaman dlm sejarah Eropah antara zaman purbakala dan zaman baru (meliputi jangka masa antara kira-kira tahun 476 hingga 1453M).','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,'ꦲꦧꦢ꧀',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (7,'berabad-abad',NULL,0,'برابد۲','Beratus-ratus tahun.','Sudah ~ lamanya sudah beratus-ratus tahun lamanya.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦧꦺꦫꦧꦢ꧀​ꦲꦧꦢ꧀',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (8,'abadi',NULL,0,'ابادي','Ar Ada permulaan yg tiada pengakhiran (bkn masa, kehidupan, kenangan dsb).','Kehidupan akhirat adalah kehidupan yg ~.','Kamus Dewan Edisi Keempat','Wujud atau berterusan utk selama-lamanya (sepanjang hayat dsb), tidak berkesudahan, kekal.','Keamanan yg ~.','Kamus Dewan Edisi Keempat',NULL,'Kasih sayang yg ~.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,'ꦲꦧꦢꦶ',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (9,'mengabadikan',NULL,0,'مڠاباديکن','Menjadikan abadi, mengekalkan','Kasih sayangnya terhadap gadis itu tidak dapat diabadikannya.','Kamus Dewan Edisi Keempat','Menjadikan peringatan (kenangan) yg kekal.','Hasil-hasil sastera itu diabadikan melalui percetakan.','Kamus Dewan Edisi Keempat',NULL,'Sebuah tugu utk ~ jasa askar-askar yg terkorban.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,'ꦩꦺꦔꦧꦢꦶꦏꦤ꧀',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (10,'terabadi',NULL,0,'ترابادي','Dapat diabadikan (dikekalkan).','Dgn usahanya itu ~ terus cerita-cerita rakyat.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦠꦺꦫꦧꦢꦶ',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (11,'keabadian',NULL,0,'کأبادين','Kewujudan yg abadi, kekekalan.','~ kasih sayang seorang ibu.','Kamus Dewan Edisi Keempat',NULL,'~ perdamaian dan keamanan.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,'ꦏꦧꦢꦤ꧀',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (12,'pengabadian',NULL,0,'ڤڠابادين','Perihal mengabadikan, pengekalan.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦥꦺꦔꦧꦢꦤ꧀',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (13,'abadiah',NULL,0,'ابدية','Ar Abadi.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦲꦧꦢꦃ',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (14,'abadiat',NULL,0,'ابدية','Ar Abadi.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ꦲꦧꦢꦠ꧀',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (15,'abah',NULL,0,'ابه','Arah, tuju.','Tak tentu ~nya.','Kamus Dewan Edisi Keempat','Ayah, bapa (biasanya sbg kata panggilan oleh seorang anak kpd bapanya).',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,'ꦲꦧꦃ',NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (16,'mengabah',NULL,0,NULL,'Menuju.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (17,'mengabahkan',NULL,0,NULL,'Mengarahkan, menujukan.','~ kapal ke tempat yg tertentu.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (18,'abah-abah',NULL,0,NULL,'Jw Alat, perkakas, tali-temali.','~ kuda alat kuda (spt tali kekang, pelana, dsb).','Kamus Dewan Edisi Keempat',NULL,'~ perahu tali-temali perahu.','Kamus Dewan Edisi Keempat',NULL,'~ tenun alat (perkakas) tenun.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (19,'abai',NULL,0,NULL,'Cuai, lalai.','tidak ~ dr tidak cuai (lalai) dr.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (20,'mengabaikan',NULL,0,NULL,'Tidak atau sangat sedikit memberikan perhatian kpd (seseorang atau sesuatu), tidak mengendahkan, mencuaikan, melalaikan.','~ anak isteri.','Kamus Dewan Edisi Keempat','Memandang tidak penting, tidak mempedulikan atau mengendahkan, menganggap sepi.','~ tunjuk ajar dan nasihat orang.','Kamus Dewan Edisi Keempat','Tidak menggunakan (sesuatu kesempatan, kemudahan yg disediakan, dll), membiarkan atau melepaskan, mensia-siakan','Sayang sekali peluang keemasan itu kauabaikan.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (21,'terabai',NULL,0,NULL,'Tidak diberi perhatian (bkn seseorang atau sesuatu), tidak dipedulikan (diendahkan atau digunakan), dibiarkan sahaja atau disia-siakan.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (22,'keterabaian',NULL,0,NULL,'Keadaan terabai.','~ sesuatu kelompok.','Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (23,'keabaian',NULL,0,NULL,'Perihal abai.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (24,'pengabaian',NULL,0,NULL,'Perihal atau perbuatan mengabaikan (keluarga, tugas dan tanggungjawab, nasihat dan teguran, peluang dan kemudahan, dll).',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (25,'pengabai',NULL,0,NULL,'(Orang yg sifatnya) suka mengabaikan atau sering tidak memberikan perhatian kpd sesuatu (spt tugas, tanggungjawab, dsb).',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (26,'abaimana',NULL,0,NULL,'(Sanskrit) sl dubur, kemaluan.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (27,'abaka',NULL,0,NULL,'sj tumbuhan (pokok) yg seratnya dibuat tali belati, Musa textilis.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (28,'abalone',NULL,0,NULL,'(abaloné) sj Siput drpd genus Haliotis yg boleh dimakan.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`Id`,`Word`,`Type`,`Value`,`Jawi`,`Desc`,`Example`,`Source`,`Desc2`,`Example2`,`Source2`,`Desc3`,`Example3`,`Source3`,`Desc4`,`Example4`,`Source4`,`Hanacaraka`,`Champa`,`Rencong`,`Lontara`) VALUES (29,'abang',NULL,0,NULL,'Saudara lelaki yg lebih tua drpd seseorang (biasanya seibu seayah dengannya).',NULL,'Kamus Dewan Edisi Keempat','Panggilan khususnya kpd saudara tua laki-laki, adik-beradik.',NULL,'Kamus Dewan Edisi Keempat','Panggilan kpd seseorang lelaki yg lebih tua sedikit.',NULL,'Kamus Dewan Edisi Keempat','Panggilan kpd suami.',NULL,'Kamus Dewan Edisi Keempat',NULL,NULL,NULL,NULL);
